### ISSUE TITLE
Redirection url is wrong when using Crowd

### ISSUE THREAD

**Issue by YukSeungChan** [pawelniewie/social-authentication-for-atlassian#4] opened 2016-04-07 07:36 UTC
Hello. 

I used this plugin in JIRA.  Normally work pretty well...

Sometimes, i moved wrong url when i try social login.

Correct URL: `http//jira.DOMAIN.COM/secure/RapidBoard.jspa?rapidView=99&view=detail&selectedIssue=BOARD-748#`

Wrong URL: `http://jira.DOMAIN.COMhttp//jira.DOMAIN.COM/secure/RapidBoard.jspa?rapidView=99&view=detail&selectedIssue=BOARD-748#`

**Comment by pawelniewie** [comment] 2016-04-07 07:38
Thanks for raising this. Are you running JIRA standalone with the Tomcat provided? Or did you deploy it as a WAR?

What version do you use?

Is there any proxy between JIRA and your browser?

**Comment by YukSeungChan** [comment] 2016-04-07 07:41
My JIRA running on my tomcat server. And i'm using nginx with reverse proxy.

Before, I'm modified server.xml like this.
```
<Connector port="8082"
                maxThreads="150"
                minSpareThreads="25"
                connectionTimeout="20000"

                enableLookups="false"
                maxHttpHeaderSize="8192"
                protocol="HTTP/1.1"
                useBodyEncodingForURI="true"
                redirectPort="8443"
                acceptCount="100"
                disableUploadTimeout="true"
                proxyName="jira.DOMAIN.COM"
                proxyPort="80"/>
```

**Comment by pawelniewie** [comment] 2016-04-07 07:42
Can you also paste nginx configuration for JIRA?

**Comment by YukSeungChan** [comment] 2016-04-07 07:44
Sure.

```
server {
    listen *:80;
    server_name jira.DOMAIN.COM;
    location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:8082;
        client_max_body_size 10M;
    }
}
```

And before i modified Engine configuration of Jira Like this
```
<Engine name="Catalina" defaultHost="localhost">
            <Host name="localhost" appBase="webapps" unpackWARs="true" autoDeploy="true">

                <Context path="" docBase="${catalina.home}/atlassian-jira" reloadable="false" useHttpOnly="true">
....
```

**Comment by pawelniewie** [comment] 2016-04-10 08:13
So far I wasn't able to reproduce it, still trying though.

**Comment by spenserpat** [comment] 2016-04-10 11:39
It may be Crowd, making some changes today. Will let you know.

> On Apr 10, 2016, at 4:13 AM, Pawel Niewiadomski <notifications@github.com> wrote:
> 
> So far I wasn't able to reproduce it, still trying though.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 

-- 
_______________________
Confidentiality Notice: This email (and any attachments) contains the 
proprietary information of New Classrooms Innovation Partners or its 
affiliates. It is for the sole use of the intended recipient and may 
contain confidential information. Confidential information includes, but is 
not limited to, personally identifiable information and information about 
program design and specifications. If you are not the intended recipient, 
you are hereby notified that any dissemination, distribution, or copying of 
this email is strictly prohibited.

**Comment by anbeque** [comment] 2016-04-27 10:49
Hi, we are facing the same issue with v2.6.0 of this plugin installed in JIRA. Any update on this?

Thanks!

**Comment by pawelniewie** [comment] 2016-04-27 11:20
@anbeque nope, as I mentioned I wasn't able to reproduce this. How do you have your JIRA set up? Do you use Crowd as well?

**Comment by spenserpat** [comment] 2016-04-27 13:00
We had to fully disconnect Crowd, and then restart Confluence. After that, it worked.

**Comment by pawelniewie** [comment] 2016-04-27 13:08
@spenserpat thanks, that's a valuable observation. Gonna play with Crowd then.

**Comment by pawelniewie** [comment] 2017-10-23 21:55
I think that's been fixed in 3.x

**Closed by pawelniewie** 2017-10-23 21:55 UTC
